### ISSUE TITLE
Wrong ")" at line 727 of fb2-reader.el

### ISSUE THREAD

**Issue by incrneg1** [jumper047/fb2-reader#3]
I'm sorry, but there are wrong ")" at near the end of line 727 of fb2-reader.el
So, it failed with syntax error. And melpa package are not usable.

diff --git a/fb2-reader.el b/fb2-reader.el
index 6321868..08d7bd1 100644
--- a/fb2-reader.el
+++ b/fb2-reader.el
@@ -724,7 +724,7 @@ header line and text for echo."
          header-line-format 'fb2-reader-header-line-format))
    (t
     (setq fb2-reader-header-line-toc nil
-         header-line-format nil))))
+         header-line-format nil)))
 
 
   (save-excursion

**Comment by jumper047** [comment]
Thank you for reporting - lines 726:759 should be deleted, I forgot to delete old functions body before commit, sorry for that.

**Comment by jumper047** [comment]
Seems like MELPA updated package, all should be fine now.
And I should set up precommit tests before next improvements:)
